# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Annlee Li
tagline:          'Hero'
description:      '2A Computer Science student at UWaterloo'
url:              http://annlee.li
baseurl:          /

author:
  name:           'Annlee Li'
  url:            https://twitter.com/tisannlee

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/annleeli

# Prose
prose:
  siteurl: "polkabear.github.io"
  media: "images"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
